version: '3'
services:
    web:
      container_name: TID-APP
      image: j3ang/tid:v1.0.3
      build: .
      volumes:
       - .:/usr/src/app
       - /usr/src/app/node_modules
      ports:
       - "80:3000"
      links:
       - mongo
      depends_on: 
       - mongo
    mongo:
      container_name: TID-DB
      image: mongo:latest
      volumes:
       - tid-mongodbdata:/data/db
      ports: 
       - "27017:27017"


volumes:
    tid-mongodbdata:

